spring:
  application:
    name: order-service-test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  flyway:
    enabled: false

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    user:
      name: testuser
      password: testpass
      roles: ADMIN

logging:
  level:
    com.orderapp: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
